<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\User;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        if (Book::query()->exists()) {
            return;
        }

        $user = User::query()->where('email', 'demo@bookstore.test')->firstOrFail();

        foreach ($this->books() as $book) {
            $user->books()->create($book);
        }
    }

    private function books(): array
    {
        return [
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'genre' => 'engineering',
                'year' => 2008,
                'pages' => 464,
                'price' => 2490,
                'old_price' => 3290,
                'rating' => 4.7,
                'reviews' => 1842,
                'in_stock' => true,
                'badge' => 'hit',
                'language' => 'EN',
                'description' => 'Практики читаемого кода, нейминг, функции и работа с легаси. База, которую ждут на любом собеседовании.',
                'cover' => ['from' => '#0f3d4c', 'to' => '#082f49', 'accent' => '#38bdf8'],
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt, David Thomas',
                'genre' => 'career',
                'year' => 2019,
                'pages' => 352,
                'price' => 2790,
                'old_price' => null,
                'rating' => 4.8,
                'reviews' => 2104,
                'in_stock' => true,
                'badge' => 'hit',
                'language' => 'EN',
                'description' => 'Мышление инженера: ортогональность, DRY, оценку, инструменты. Не фреймворк — операционная система карьеры.',
                'cover' => ['from' => '#3f1d12', 'to' => '#1c1917', 'accent' => '#fb923c'],
            ],
            [
                'title' => 'Designing Data-Intensive Applications',
                'author' => 'Martin Kleppmann',
                'genre' => 'architecture',
                'year' => 2017,
                'pages' => 616,
                'price' => 3990,
                'old_price' => 4590,
                'rating' => 4.9,
                'reviews' => 3260,
                'in_stock' => true,
                'badge' => 'hit',
                'language' => 'EN',
                'description' => 'Репликация, партиционирование, транзакции, стриминг. Книга, без которой разговор про highload выглядит пустым.',
                'cover' => ['from' => '#1e1b4b', 'to' => '#0f172a', 'accent' => '#818cf8'],
            ],
            [
                'title' => 'Refactoring',
                'author' => 'Martin Fowler',
                'genre' => 'engineering',
                'year' => 2018,
                'pages' => 448,
                'price' => 3190,
                'old_price' => null,
                'rating' => 4.6,
                'reviews' => 987,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Каталог рефакторингов и запахов кода. Как менять структуру, не ломая поведение — и когда это вообще стоит делать.',
                'cover' => ['from' => '#422006', 'to' => '#1c1917', 'accent' => '#fbbf24'],
            ],
            [
                'title' => 'Design Patterns',
                'author' => 'Gamma, Helm, Johnson, Vlissides',
                'genre' => 'architecture',
                'year' => 1994,
                'pages' => 395,
                'price' => 2890,
                'old_price' => 3490,
                'rating' => 4.4,
                'reviews' => 1540,
                'in_stock' => true,
                'badge' => 'sale',
                'language' => 'EN',
                'description' => 'GoF. Не заучивать диаграммы — понимать constrains. Strategy, Decorator, Observer до сих пор живут во Vue и Laravel.',
                'cover' => ['from' => '#3b0764', 'to' => '#1e1b4b', 'accent' => '#c084fc'],
            ],
            [
                'title' => "You Don't Know JS Yet",
                'author' => 'Kyle Simpson',
                'genre' => 'frontend',
                'year' => 2020,
                'pages' => 278,
                'price' => 1990,
                'old_price' => null,
                'rating' => 4.5,
                'reviews' => 2211,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Scopes, closures, this, прототипы. То, что отделяет «пишу на Vue» от «понимаю, что делает runtime».',
                'cover' => ['from' => '#713f12', 'to' => '#171717', 'accent' => '#facc15'],
            ],
            [
                'title' => 'Vue.js: The Complete Guide',
                'author' => 'Maximilian Schwarzmüller',
                'genre' => 'frontend',
                'year' => 2024,
                'pages' => 512,
                'price' => 2590,
                'old_price' => null,
                'rating' => 4.6,
                'reviews' => 640,
                'in_stock' => true,
                'badge' => 'new',
                'language' => 'EN',
                'description' => 'Composition API, reactivity, роутер, состояние. Практический слой поверх спецификации Vue 3.',
                'cover' => ['from' => '#14532d', 'to' => '#052e16', 'accent' => '#4ade80'],
            ],
            [
                'title' => 'Laravel: Up & Running',
                'author' => 'Matt Stauffer',
                'genre' => 'backend',
                'year' => 2023,
                'pages' => 544,
                'price' => 3290,
                'old_price' => 3790,
                'rating' => 4.5,
                'reviews' => 412,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Маршруты, контейнер, Eloquent, очереди, тестирование. Как устроен Laravel, а не только artisan make:controller.',
                'cover' => ['from' => '#7f1d1d', 'to' => '#1c1917', 'accent' => '#f87171'],
            ],
            [
                'title' => 'Domain-Driven Design',
                'author' => 'Eric Evans',
                'genre' => 'architecture',
                'year' => 2003,
                'pages' => 560,
                'price' => 3690,
                'old_price' => null,
                'rating' => 4.3,
                'reviews' => 890,
                'in_stock' => false,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Bounded contexts, ubiquitous language, агрегаты. Тяжёлая, но это словарь, на котором говорят архитекторы.',
                'cover' => ['from' => '#0c4a6e', 'to' => '#082f49', 'accent' => '#7dd3fc'],
            ],
            [
                'title' => 'Grokking Algorithms',
                'author' => 'Aditya Bhargava',
                'genre' => 'algorithms',
                'year' => 2016,
                'pages' => 256,
                'price' => 2190,
                'old_price' => 2690,
                'rating' => 4.7,
                'reviews' => 3012,
                'in_stock' => true,
                'badge' => 'sale',
                'language' => 'EN',
                'description' => 'Бинарный поиск, графы, жадные алгоритмы — без академического тумана. Хороший прогрев перед leetcode.',
                'cover' => ['from' => '#134e4a', 'to' => '#042f2e', 'accent' => '#2dd4bf'],
            ],
            [
                'title' => 'Staff Engineer',
                'author' => 'Will Larson',
                'genre' => 'career',
                'year' => 2021,
                'pages' => 237,
                'price' => 2390,
                'old_price' => null,
                'rating' => 4.6,
                'reviews' => 754,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Как расти без менеджмента: влияние, техстратегия, работа со стейкхолдерами. Карта ролей после senior.',
                'cover' => ['from' => '#1e3a5f', 'to' => '#0b1220', 'accent' => '#60a5fa'],
            ],
            [
                'title' => 'Kubernetes in Action',
                'author' => 'Marko Lukša',
                'genre' => 'devops',
                'year' => 2022,
                'pages' => 700,
                'price' => 4290,
                'old_price' => null,
                'rating' => 4.5,
                'reviews' => 528,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Поды, сервисы, деплойменты, сеть. Не «yaml-копипаста», а модель, из которой собирается прод.',
                'cover' => ['from' => '#1e3a8a', 'to' => '#172554', 'accent' => '#93c5fd'],
            ],
            [
                'title' => 'SQL Performance Explained',
                'author' => 'Markus Winand',
                'genre' => 'backend',
                'year' => 2012,
                'pages' => 204,
                'price' => 1890,
                'old_price' => null,
                'rating' => 4.8,
                'reviews' => 1103,
                'in_stock' => true,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Индексы, explain, сортировки, join. После неё N+1 и «добавим индекс на всё» звучат как антипаттерны.',
                'cover' => ['from' => '#44403c', 'to' => '#1c1917', 'accent' => '#a8a29e'],
            ],
            [
                'title' => 'Working Effectively with Legacy Code',
                'author' => 'Michael Feathers',
                'genre' => 'engineering',
                'year' => 2004,
                'pages' => 456,
                'price' => 2990,
                'old_price' => 3490,
                'rating' => 4.5,
                'reviews' => 671,
                'in_stock' => true,
                'badge' => 'sale',
                'language' => 'EN',
                'description' => 'Швы, characterization-тесты, как вскрыть модуль без полного переписывания. Реальность большинства кодовых баз.',
                'cover' => ['from' => '#4a044e', 'to' => '#1e1b4b', 'accent' => '#e879f9'],
            ],
            [
                'title' => 'The Mythical Man-Month',
                'author' => 'Frederick Brooks',
                'genre' => 'career',
                'year' => 1995,
                'pages' => 336,
                'price' => 1790,
                'old_price' => null,
                'rating' => 4.4,
                'reviews' => 1433,
                'in_stock' => false,
                'badge' => null,
                'language' => 'EN',
                'description' => 'Почему девять женщин не рожают за месяц. Классика эстимаций, коммуникации и провала «ещё людей в проект».',
                'cover' => ['from' => '#7c2d12', 'to' => '#1c1917', 'accent' => '#fdba74'],
            ],
            [
                'title' => 'Site Reliability Engineering',
                'author' => 'Betsy Beyer et al.',
                'genre' => 'devops',
                'year' => 2024,
                'pages' => 552,
                'price' => 3590,
                'old_price' => null,
                'rating' => 4.6,
                'reviews' => 390,
                'in_stock' => true,
                'badge' => 'new',
                'language' => 'EN',
                'description' => 'SLO, error budgets, toil, инциденты. Как Google думает про надёжность — применимо и к одному Docker-хосту.',
                'cover' => ['from' => '#0f766e', 'to' => '#134e4a', 'accent' => '#5eead4'],
            ],
        ];
    }
}
